### PR TITLE
Cf 548 - Investigate spark 1.2 to allow order by timestamp

### PR DESCRIPTION
**Pull request by usnavi**
Tested spark 1.2 on our test node & updated code to order entries by datelastupdated timestamp.

Please first accept:  https://github.com/rackerlabs/cloudfeeds-nabu/pull/8

### CODE REVIEW

**Comment by shintasmith** [comment]
Looks like this PR has both PR #8 and spark changes in one? Would it be possible to rebase or merge upstream so I can see the only changes for this PR?

**Comment by usnavi** [comment]
done!

**Comment by shintasmith** [comment]
@usnavi, lgtm. Do you want me to merge this? Or wait until you tested Spark 1.2 on HDP 2.1?

**Comment by usnavi** [comment]
merge this.  It's required, so we definitely need to use spark 1.2.

**Pull request merged**
