### PR TITLE
CF-703: create success.txt file on successful daily run of Usmu workflow

### PR DESCRIPTION
**Pull request by shintasmith**
Changes to support a more seamless integration with Tiamat and to support monitoring:
* add a workflow fs action to create an empty ```success.txt``` file on successful run of the daily workflow
* add configuration for the top directory location in HDFS for the success file in the *.properties file
* change default values of some locations to /user/cloudfeeds

### CODE REVIEW

**Comment by ChandraAddala** [comment]
Looks good to me. @usnavi can review and merge.

**Comment by usnavi** [comment]
FYI - tiamat is creating a file called /var/log/cloudfeeds-nabu/tiamat/last_success.txt - should we have the same name?

**Comment by shintasmith** [comment]
Tiamat is a bit different I think. It is a cron job and the file will be created on the local file system. This file Usmu is creating will be in HDFS. I can put succes.txt file in /var/log/cloudfeeds-nabu/usmu, but it will be in HDFS. So something like this:
```
hdfs://nameNode/var/log/cloudfeeds-nabu/usmu/DFW/2015-04-12/success.txt
```
Also, I can not put timestamp in that file -- I haven't found a way in Oozie to do that.

Do you still think there is a merit to do it that way, given the differences? It's just a matter of changing a variable in *.properties file and re-test.

**Comment by usnavi** [comment]
lgtm; no timestamp in the success.txt file is required since the date will be in path.  Also, it will be monitored differently than tiamat.

**Pull request merged**
