### PR TITLE
moving to ORC; works with hive .14 & spark 1.2

### PR DESCRIPTION
**Pull request by usnavi**

### CODE REVIEW

**Comment by ChandraAddala** [comment]
Too much code! You better refactor.

**Comment by usnavi** [comment]
I see where you're going.  You want me to do it in python!

**Comment by shintasmith** [comment]
back to ORC, huh :-)

**Comment by shintasmith** [comment]
ok..... if you must

**Comment by usnavi** [comment]
parquet no worky with hive .14 and timestamps.  buggy, buggy.

**Pull request merged**
